myproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls'))
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
urlpatterns =[
    path('',views.index,name='pagehome'),
    path('Lighting.html',views.light,name='lightpage'),
    path('Furniture.html',views.furniture,name='furniture'),
    path('Storage Organization.html',views.sao,name='SAOpage'),
    path('Wall Art.html',views.art,name='wallartpage'),
    path('buy/<int:product_id>/', views.buy, name='buy'),
    path('confirmation_page.html',views.confirmation,name='confirmation_page')
]

store/models.py
from django.db import models 
import datetime 
#categories table  
class Category(models.Model): 
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name 
  
# 
class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField()
    image = models.ImageField(upload_to='images')
class User(models.Model):
    name = models.CharField(max_length=50)
    telephone = models.CharField(max_length=20)
    ville = models.CharField(max_length=30)
    address = models.CharField(max_length=255)
class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    order_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, default='Pending') 

store/views.py
from django.shortcuts import render,redirect
from .models import Product
from .models import Category
from .models import Order, User
categories = Category.objects.all()
products = Product.objects.all()
def index(request) :
    new_products = [product for product in products if len(product.description) < 60]
    new_products = list(reversed(new_products))[:6]
    return render(request,'page_home.html',{'products': new_products , 'categories':categories})

def light (request): 
    lighting_category = Category.objects.get(name='Lighting')
    lighting_products = Product.objects.filter(category=lighting_category)
    return render(request,'Lighting.html',{'lighting_products':lighting_products,'categories':categories})

def furniture(request):
    furniture_category = Category.objects.get(name='Furniture')
    furniture_products = Product.objects.filter(category=furniture_category)
    return render(request,'Furniture.html',{'furniture_products':furniture_products,'categories':categories})

def sao(request):
    sao_category = Category.objects.get(name='Storage Organization')
    sao_products = Product.objects.filter(category=sao_category)
    return render(request,'Storage Organization.html',{'sao_products':sao_products,'categories':categories})

def art(request):
    wallart_category = Category.objects.get(name='Wall Art')
    wallart_products = Product.objects.filter(category=wallart_category)
    return render(request,'Wall Art.html',{'wallart_products':wallart_products,'categories':categories})

from django.shortcuts import render, redirect
from .models import User, Order

def buy(request, product_id):
    if request.method == 'POST':
        # Récupérer les données du formulaire
        name = request.POST.get('name')
        telephone = request.POST.get('telephone')
        ville = request.POST.get('ville')
        address = request.POST.get('address')
        quantity = request.POST.get('quantity')
        
        # Vérifier si l'utilisateur existe déjà
        user, created = User.objects.get_or_create(
            name=name,
            telephone=telephone,
            ville=ville,
            address=address
        )
        
        # Récupérer le produit en fonction de son ID
        product = Product.objects.get(id=product_id)
        
        # Créer une instance Order et l'enregistrer dans la base de données
        order = Order.objects.create(product=product, user=user, quantity=quantity)
        
        # Rediriger l'utilisateur vers une page de confirmation ou toute autre page nécessaire
        return redirect('confirmation_page')  # Assurez-vous d'avoir une URL nommée pour la page de confirmation dans vos URLs
        
    else:
        # Si la méthode de requête n'est pas POST, afficher le formulaire
        return render(request, 'buy.html', {'product_id': product_id,'categories':categories})

def confirmation(request):
    return render(request, 'confirmation_page.html')

templates/Furniture.html
{% extends 'nav.html' %}
{% block content %}
{% load static%}
<br>
   <!DOCTYPE html>
   <html lang="en">
   <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Document</title>
    <style>
        .lightcategories{
            width: 90%;
            margin: 0 40px;
            margin-top: 100px;
            display:flex;
            align-items: center;
            justify-content: center;
            gap: 40px;
            flex-wrap: wrap;
        }
    </style>
   </head>
   <body>
    <div class="lightcategories">
        {% for furniture_product in furniture_products %}
        <div class="card" style="width: 18rem;border-radius: 30px;">
            <img src="{{ furniture_product.image.url }}" class="card-img-top hover-scale" alt="..." height="300px" style="border-radius: 40px; padding: 8px;">
            <div class="card-body">
              <h5 class="card-title d-flex justify-content-between">{{ furniture_product.name }} <span>{{furniture_product.price}}$</span></h5>
              <p class="card-text">{{ furniture_product.description }}</p>
              <div class="action d-flex justify-content-between">
                <a href="#" class="btn">More Details</a>
                <a href="#" class="btn btn-danger">Buy Now</a>
              </div>
            </div>
          </div>
        {% endfor%}
    </div>
   </body>
   </html>
{% endblock content%}

templates/Lighting.html
{% extends 'nav.html' %}
{% block content %}
{% load static%}
<br>
   <!DOCTYPE html>
   <html lang="en">
   <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Document</title>
    <style>
        .lightcategories{
            width: 90%;
            margin: 0 40px;
            margin-top: 100px;
            display:flex;
            align-items: center;
            justify-content: center;
            gap: 40px;
            flex-wrap: wrap;
        }
    </style>
   </head>
   <body>
    <div class="lightcategories">
        {% for light_product in lighting_products %}
        <div class="card" style="width: 18rem;border-radius: 30px;">
            <img src="{{ light_product.image.url }}" class="card-img-top hover-scale" alt="..." height="300px" style="border-radius: 40px; padding: 8px;">
            <div class="card-body">
              <h5 class="card-title d-flex justify-content-between">{{ light_product.name }} <span>{{light_product.price}}$</span></h5>
              <p class="card-text">{{ light_product.description }}</p>
              <div class="action d-flex justify-content-between">
                <a href="#" class="btn">More Details</a>
                <a href="#" class="btn btn-danger">Buy Now</a>
              </div>
            </div>
          </div>
        {% endfor%}
    </div>
   </body>
   </html>
{% endblock content%}

templates/Storage Organization.html
{% extends 'nav.html' %}
{% block content %}
{% load static%}
<br>
   <!DOCTYPE html>
   <html lang="en">
   <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Document</title>
    <style>
        .lightcategories{
            width: 90%;
            margin: 0 40px;
            margin-top: 100px;
            display:flex;
            align-items: center;
            justify-content: center;
            gap: 40px;
            flex-wrap: wrap;
        }
    </style>
   </head>
   <body>
    <div class="lightcategories">
        {% for sao_product in sao_products %}
        <div class="card" style="width: 18rem;border-radius: 30px;">
            <img src="{{ sao_product.image.url }}" class="card-img-top hover-scale" alt="..." height="300px" style="border-radius: 40px; padding: 8px;">
            <div class="card-body">
              <h5 class="card-title d-flex justify-content-between">{{ sao_product.name }} <span>{{sao_product.price}}$</span></h5>
              <p class="card-text">{{ sao_product.description }}</p>
              <div class="action d-flex justify-content-between">
                <a href="#" class="btn">More Details</a>
                <a href="#" class="btn btn-danger">Buy Now</a>
              </div>
            </div>
          </div>
        {% endfor%}
    </div>
   </body>
   </html>
{% endblock content%}

templates/Wall Art.html
{% extends 'nav.html' %}
{% block content %}
{% load static%}
<br>
   <!DOCTYPE html>
   <html lang="en">
   <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Document</title>
    <style>
        .lightcategories{
            width: 90%;
            margin: 0 40px;
            margin-top: 100px;
            display:flex;
            align-items: center;
            justify-content: center;
            gap: 40px;
            flex-wrap: wrap;
        }
    </style>
   </head>
   <body>
    <div class="lightcategories">
        {% for wallart_product in wallart_products %}
        <div class="card" style="width: 18rem;border-radius: 30px;">
            <img src="{{ wallart_product.image.url }}" class="card-img-top hover-scale" alt="..." height="300px" style="border-radius: 40px; padding: 8px;">
            <div class="card-body">
              <h5 class="card-title d-flex justify-content-between">{{wallart_product.name }} <span>{{wallart_product.price}}$</span></h5>
              <p class="card-text">{{ wallart_product.description }}</p>
              <div class="action d-flex justify-content-between">
                <a href="#" class="btn">More Details</a>
                <a href="{% url 'buy' product_id=wallart_product.id %}" class="btn btn-danger">Buy Now</a>
              </div>
            </div>
          </div>
        {% endfor%}
    </div>
   </body>
   </html>
{% endblock content%}

templates/buy.html
{% extends 'nav.html' %}
{% block content%}
{% load static%}
<br><br><br>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        section{
            height: 450px;
            width: 75%;
            margin: 15px auto;
            background: #fff;
            border-radius: 10px;
            display: flex;
            justify-content: space-around;
            align-items: center;
        }
        section .orderimg{
            width: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        section .orderimg img{
            border: 1px solid var(--light);
        }
        section .Order{
            width: 40%;
            height: 400px;
            display: flex;
            align-items: center;
            justify-content: center;
            border: 2px solid var(--light);
            border-radius: 10px;
    
        }

        form input{
            width: 250px;
            border: 1px solid var(--light);
            border-radius: 5px;
            padding: 3px;
        }
        form h2{
            margin-top: 25px;
            margin-bottom: 15px;
        }
        form div {
            display: flex;
            align-items: center;
            justify-content: end;
            margin-bottom: 20px;
        }
        form div .btn{
            margin: 2px;
            width: 100%;
            height: 40px;
            border-radius: 10px;
            color: #fff;
            border : none;
        }
        
    </style>
    <title>Order Form</title>
</head>
<body>
    <section>
        <div class="orderimg">
            <img src="{%static 'images/c49a207e0f89c9290d98fd43a87a8cb0.gif'%}" alt="" width="400px">
        </div>
        <div class="Order">
            <div class="buy_infos">
                <form method="post" >
                    <h2>Order information</h2>
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value ='{{product_id}}'>
                    <input type="text" id="id_nom" name="name" required placeholder="Enter your name :"><br><br>
                    <input type="tel" id="id_telephone" name="telephone" required placeholder="Enter your phone :"><br><br>

                    <input type="text" id="ville" name="ville" required placeholder="Enter your city :"><br><br>

                    <input type="text" id="id_address" name="address" required placeholder="Enter your address:"><br><br>
        
                    <input type="number" id="id_quantity" name="quantity" min="1" required placeholder="Enter the quantity :"><br><br>
                    <div><button  class="btn btn-warning" type="submit">BUY</button></div>
                </form>
            </div>
        </div>
    </section>
</body>
</html>
{% endblock content %}

templates/confirmation_page.html
{% block content %}
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body{
            height: 100vh;
            background: #dfe1e2f3;
        }
        .center{
            width: 80%;
            height: 500px;
            margin: 20px auto;
            margin-top: 40px;
            background: url("{% static 'images/xx.gif'%}");
            background-position: center;
            z-index: 999;
        }
        .center h1{
            color: green;
            text-align: center;
            padding: 40px 0px;
            font-size: 50px;
        }
        .center p{
            text-align: center;
            padding: 40px;
            font-size: 20px;
        }
        .center a{
            display: block;
            text-align: center;
            
        }
    </style>
    <title>Document</title>
</head>
<body>
    <div class="center">
        
        <h1>Thank you for your order &#128525</h1>
        <br><br><br><br><br><br>
        <p>
            We'll be in touch shortly to confirm the details and ensure a smooth processing of your purchase. Your satisfaction is our priority, and we're here to assist you every step of the way. Stay tuned!
        </p>
        <a href="{% url 'pagehome'%}">Back to home</a>
    </div>
</body>
</html>
{% endblock content %}

templates/nav.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Audiowide|Sofia|Trirong">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Document</title>
</head>
<body>
  <div class="nav_container">
    <nav class="navbar">
      <a class="active" href="{% url 'pagehome' %}">
        <img class="logo" src="{% static 'images/log-removebg-preview.png'%}" alt="" width="80px">
      </a>
      <ul>
        {% for categorie in categories %}
        <li>
          <a href="{{categorie.name}}.html">{{categorie.name}}</a>
          {% endfor%}
        </li>
      </ul>
      <div class="panier">
        <a href="#">
          <i class="fa fa-user"></i>
        </a>
        <a href="#">
          <i class="fa fa-shopping-cart"></i>
        </a>
        <a href="#">
          <i class="fa fa-heart"></i>
        </a>
      </div>
    </nav>
  </div>
{%block content%}
{% endblock content%}
</body>
</html>

templates/page_home.html
{% extends 'nav.html'%}
{% block content %}
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
   <title>Document</title>
</head>
<body>
  <div class="header">
    <div class="header-content">
      <div class="content">
        <h1>Revamp Your Living Space</h1>
        <h3>Chic and Modern Décor Tips</h3>
        <form action="details.html" class="details">
          <button type="submit">Contact Us</button>
        </form>
      </div>
    </div>
</div>
<section>
  <div class="newcollection">
    <div class="newcollections-title">
      <h1>New Collection</h1>
      <p> Explore Our Collection of High-Quality and Exceptional Design</p>
    </div>
    <div class="newcollections-content d-flex justify-content-center gap-5  flex-wrap">
        {% for product in products %}
          <div class="card" style="width: 18rem;border-radius: 30px;">
            <img src="{{ product.image.url }}" class="card-img-top hover-scale" alt="..." height="300px" style="border-radius: 40px; padding: 8px;">
            <div class="card-body">
              <h5 class="card-title d-flex justify-content-between">{{ product.name }} <span>{{product.price}}$</span></h5>
              <p class="card-text">{{ product.description }}</p>
              <div class="action d-flex justify-content-between">
                <a href="{% url 'buy' product_id=product.id %}" class="btn">Buy Now</a>
              </div>
            </div>
          </div>
        {% endfor%}
    </div>
  </div>
</section>
<section>
  <div class="newcollections-title">
    <h1>The Excellence of Our Furniture</h1>
    <p> Quality, Functionality, Design, and Customer Service</p>
  </div>
  <div class="norme">
    <div class="box">
      <h3>Quality</h3>
      <div><img src="{%static 'images/controle-de-qualite.png'%}" alt="" width="80px"></div>
      <p>Our suppliers are rigorously selected for their expertise. All our furniture is made from high-quality materials and is built to last for many years.</p>
    </div>
    <div class="box">
      <h3>Functionality</h3>
      <div><img src="{%static 'images/reglage.png'%}" alt="" width="80px"></div>
      <p>Our furniture is chosen to be beautiful and comfortable, but also practical and functional.</p>
    </div>
    <div class="box">
      <h3>Design</h3>
      <div><img src="{%static 'images/art.png'%}" alt="" width="80px"></div>
      <p>We follow the latest trends and travel the world to bring you the newest designs as well as timeless models that blend into any decor.</p>
    </div>
    <div class="box">
      <h3>Customer Service</h3>
      <div><img src="{%static 'images/vente.png'%}" alt="" width="80px"></div>
      <p>We are committed to providing excellent customer service, with delivery options throughout Morocco and technical support to meet customer needs.</p>
    </div>

  </div>
</section>
</body>
</html>
{% endblock content%}